// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * FAQCreate
 */
export type FAQCreate = {
    /**
     * Category
     */
    category: string;
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
    /**
     * Display Order
     */
    display_order?: number;
};

/**
 * FAQPublic
 */
export type FAQPublic = {
    /**
     * Category
     */
    category: string;
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
    /**
     * Display Order
     */
    display_order?: number;
    /**
     * Id
     */
    id: string;
};

/**
 * FAQUpdate
 */
export type FAQUpdate = {
    /**
     * Category
     */
    category?: string | null;
    /**
     * Question
     */
    question?: string | null;
    /**
     * Answer
     */
    answer?: string | null;
    /**
     * Display Order
     */
    display_order?: number | null;
};

/**
 * FAQsPublic
 */
export type FAQsPublic = {
    /**
     * Data
     */
    data: Array<FAQPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KioskRegister
 *
 * Alta de un estudiante: sin contraseña, solo su ID y nombre.
 */
export type KioskRegister = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * KioskRegisterResponse
 */
export type KioskRegisterResponse = {
    token: Token;
    /**
     * Qr Token
     */
    qr_token: string;
    user: UserPublic;
};

/**
 * KioskSession
 */
export type KioskSession = {
    /**
     * Student Id
     */
    student_id: string;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ParkingLogAction
 */
export type ParkingLogAction = 'payment_created' | 'payment_approved' | 'payment_declined' | 'plan_activated' | 'plan_renewed';

/**
 * ParkingLogPublic
 */
export type ParkingLogPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Payment Id
     */
    payment_id: string | null;
    action: ParkingLogAction;
    /**
     * Detail
     */
    detail: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ParkingLogsPublic
 */
export type ParkingLogsPublic = {
    /**
     * Data
     */
    data: Array<ParkingLogPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PaymentConcept
 */
export type PaymentConcept = 'daily_fee' | 'recharge' | 'plan_purchase' | 'plan_renewal';

/**
 * PaymentInitiate
 *
 * Lo único que el cliente puede pedir: qué quiere pagar, no cuánto ni el
 * estado. La excepción es `amount_cop`, que solo se usa (y solo tiene
 * sentido) para el concepto RECHARGE, donde el monto es una elección
 * legítima del usuario; para cualquier otro concepto el servidor lo ignora
 * y calcula el monto real a partir del catálogo correspondiente.
 */
export type PaymentInitiate = {
    concept: PaymentConcept;
    /**
     * Method Id
     */
    method_id: string;
    /**
     * Vehicle Id
     */
    vehicle_id?: string | null;
    /**
     * Plan Id
     */
    plan_id?: string | null;
    /**
     * Amount Cop
     */
    amount_cop?: number | null;
};

/**
 * PaymentInitiateResponse
 */
export type PaymentInitiateResponse = {
    /**
     * Id
     */
    id: string;
    concept: PaymentConcept;
    /**
     * Amount Cop
     */
    amount_cop: number;
    /**
     * Method Code
     */
    method_code: string;
    /**
     * Method Name
     */
    method_name: string;
    status_code: PaymentStatusCode;
    /**
     * Wompi Reference
     */
    wompi_reference: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Wompi Public Key
     */
    wompi_public_key: string;
    /**
     * Amount In Cents
     */
    amount_in_cents: number;
    /**
     * Integrity Signature
     */
    integrity_signature: string;
    /**
     * Redirect Url
     */
    redirect_url: string;
};

/**
 * PaymentMethodPublic
 */
export type PaymentMethodPublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Id
     */
    id: string;
};

/**
 * PaymentPublic
 */
export type PaymentPublic = {
    /**
     * Id
     */
    id: string;
    concept: PaymentConcept;
    /**
     * Amount Cop
     */
    amount_cop: number;
    /**
     * Method Code
     */
    method_code: string;
    /**
     * Method Name
     */
    method_name: string;
    status_code: PaymentStatusCode;
    /**
     * Wompi Reference
     */
    wompi_reference: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * PaymentStatusCode
 */
export type PaymentStatusCode = 'pending' | 'approved' | 'declined' | 'cancelled';

/**
 * PaymentsPublic
 */
export type PaymentsPublic = {
    /**
     * Data
     */
    data: Array<PaymentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PlanCreate
 */
export type PlanCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Price Cop
     */
    price_cop: number;
    /**
     * Duration Days
     */
    duration_days: number;
    /**
     * Conditions
     */
    conditions?: string | null;
    /**
     * Active
     */
    active?: boolean;
    /**
     * Vehicle Type Id
     */
    vehicle_type_id?: string | null;
};

/**
 * PlanPublic
 */
export type PlanPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Price Cop
     */
    price_cop: number;
    /**
     * Duration Days
     */
    duration_days: number;
    /**
     * Conditions
     */
    conditions?: string | null;
    /**
     * Active
     */
    active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Vehicle Type Id
     */
    vehicle_type_id?: string | null;
};

/**
 * PlanUpdate
 */
export type PlanUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Price Cop
     */
    price_cop?: number | null;
    /**
     * Duration Days
     */
    duration_days?: number | null;
    /**
     * Conditions
     */
    conditions?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
};

/**
 * PlansPublic
 */
export type PlansPublic = {
    /**
     * Data
     */
    data: Array<PlanPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * PushSubscriptionCreate
 */
export type PushSubscriptionCreate = {
    /**
     * Endpoint
     */
    endpoint: string;
    /**
     * P256Dh
     */
    p256dh: string;
    /**
     * Auth
     */
    auth: string;
};

/**
 * QRSession
 */
export type QRSession = {
    /**
     * Qr Token
     */
    qr_token: string;
};

/**
 * StaffRegister
 *
 * Alta de personal de UNIMINUTO exento de pago (solo un admin puede crearla).
 */
export type StaffRegister = {
    /**
     * Student Id
     */
    student_id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * SubscriptionPublic
 */
export type SubscriptionPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Plan Id
     */
    plan_id: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Active
     */
    active: boolean;
};

/**
 * SupportTicketCreate
 */
export type SupportTicketCreate = {
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
};

/**
 * SupportTicketPublic
 */
export type SupportTicketPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Case Number
     */
    case_number: string;
    /**
     * Subject
     */
    subject: string;
    /**
     * Message
     */
    message: string;
    status: SupportTicketStatus;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * SupportTicketStatus
 */
export type SupportTicketStatus = 'open' | 'in_progress' | 'resolved' | 'closed';

/**
 * SupportTicketUpdateStatus
 */
export type SupportTicketUpdateStatus = {
    status: SupportTicketStatus;
};

/**
 * SupportTicketsPublic
 */
export type SupportTicketsPublic = {
    /**
     * Data
     */
    data: Array<SupportTicketPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 *
 * Solo para cuentas administradas (superusuario / admin), con contraseña.
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Student Id
     */
    student_id?: string | null;
    role?: UserRole;
    /**
     * Plan Until
     */
    plan_until?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Student Id
     */
    student_id?: string | null;
    role: UserRole;
    /**
     * Plan Until
     */
    plan_until?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRole
 */
export type UserRole = 'ESTUDIANTE' | 'EXENTO';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * VehicleCreate
 */
export type VehicleCreate = {
    /**
     * Plate
     */
    plate: string;
    /**
     * Type Id
     */
    type_id: string;
};

/**
 * VehiclePublic
 */
export type VehiclePublic = {
    /**
     * Plate
     */
    plate: string;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Type Id
     */
    type_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * VehicleTypePublic
 */
export type VehicleTypePublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Daily Rate Cop
     */
    daily_rate_cop: number;
    /**
     * Id
     */
    id: string;
};

/**
 * VehiclesPublic
 */
export type VehiclesPublic = {
    /**
     * Data
     */
    data: Array<VehiclePublic>;
    /**
     * Count
     */
    count: number;
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type kioskRegisterData = {
    body: KioskRegister;
    path?: never;
    query?: never;
    url: '/api/v1/kiosk/register';
};

export type kioskRegisterErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type kioskRegisterError = kioskRegisterErrors[keyof kioskRegisterErrors];

export type kioskRegisterResponses = {
    /**
     * Successful Response
     */
    200: KioskRegisterResponse;
};

export type kioskRegisterResponse = kioskRegisterResponses[keyof kioskRegisterResponses];

export type kioskRegisterStaffData = {
    body: StaffRegister;
    path?: never;
    query?: never;
    url: '/api/v1/kiosk/register-staff';
};

export type kioskRegisterStaffErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type kioskRegisterStaffError = kioskRegisterStaffErrors[keyof kioskRegisterStaffErrors];

export type kioskRegisterStaffResponses = {
    /**
     * Successful Response
     */
    200: KioskRegisterResponse;
};

export type kioskRegisterStaffResponse = kioskRegisterStaffResponses[keyof kioskRegisterStaffResponses];

export type kioskSessionByStudentIdData = {
    body: KioskSession;
    path?: never;
    query?: never;
    url: '/api/v1/kiosk/session';
};

export type kioskSessionByStudentIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type kioskSessionByStudentIdError = kioskSessionByStudentIdErrors[keyof kioskSessionByStudentIdErrors];

export type kioskSessionByStudentIdResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type kioskSessionByStudentIdResponse = kioskSessionByStudentIdResponses[keyof kioskSessionByStudentIdResponses];

export type kioskSessionByQrData = {
    body: QRSession;
    path?: never;
    query?: never;
    url: '/api/v1/kiosk/qr-session';
};

export type kioskSessionByQrErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type kioskSessionByQrError = kioskSessionByQrErrors[keyof kioskSessionByQrErrors];

export type kioskSessionByQrResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type kioskSessionByQrResponse = kioskSessionByQrResponses[keyof kioskSessionByQrResponses];

export type kioskMyQrData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/kiosk/my-qr';
};

export type kioskMyQrResponses = {
    /**
     * Response Kiosk-My Qr
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type kioskMyQrResponse = kioskMyQrResponses[keyof kioskMyQrResponses];

export type kioskRegenerateQrData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/kiosk/regenerate-qr';
};

export type kioskRegenerateQrResponses = {
    /**
     * Response Kiosk-Regenerate Qr
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type kioskRegenerateQrResponse = kioskRegenerateQrResponses[keyof kioskRegenerateQrResponses];

export type kioskVerifyQrData = {
    body: QRSession;
    path?: never;
    query?: never;
    url: '/api/v1/kiosk/verify-qr';
};

export type kioskVerifyQrErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type kioskVerifyQrError = kioskVerifyQrErrors[keyof kioskVerifyQrErrors];

export type kioskVerifyQrResponses = {
    /**
     * Response Kiosk-Verify Qr
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type kioskVerifyQrResponse = kioskVerifyQrResponses[keyof kioskVerifyQrResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type vehiclesListMyVehiclesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/vehicles/';
};

export type vehiclesListMyVehiclesResponses = {
    /**
     * Successful Response
     */
    200: VehiclesPublic;
};

export type vehiclesListMyVehiclesResponse = vehiclesListMyVehiclesResponses[keyof vehiclesListMyVehiclesResponses];

export type vehiclesRegisterVehicleData = {
    body: VehicleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/vehicles/';
};

export type vehiclesRegisterVehicleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type vehiclesRegisterVehicleError = vehiclesRegisterVehicleErrors[keyof vehiclesRegisterVehicleErrors];

export type vehiclesRegisterVehicleResponses = {
    /**
     * Successful Response
     */
    200: VehiclePublic;
};

export type vehiclesRegisterVehicleResponse = vehiclesRegisterVehicleResponses[keyof vehiclesRegisterVehicleResponses];

export type vehiclesListVehicleTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/vehicles/types';
};

export type vehiclesListVehicleTypesResponses = {
    /**
     * Response Vehicles-List Vehicle Types
     *
     * Successful Response
     */
    200: Array<VehicleTypePublic>;
};

export type vehiclesListVehicleTypesResponse = vehiclesListVehicleTypesResponses[keyof vehiclesListVehicleTypesResponses];

export type vehiclesDeleteVehicleData = {
    body?: never;
    path: {
        /**
         * Vehicle Id
         */
        vehicle_id: string;
    };
    query?: never;
    url: '/api/v1/vehicles/{vehicle_id}';
};

export type vehiclesDeleteVehicleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type vehiclesDeleteVehicleError = vehiclesDeleteVehicleErrors[keyof vehiclesDeleteVehicleErrors];

export type vehiclesDeleteVehicleResponses = {
    /**
     * Response Vehicles-Delete Vehicle
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type vehiclesDeleteVehicleResponse = vehiclesDeleteVehicleResponses[keyof vehiclesDeleteVehicleResponses];

export type paymentsListPaymentMethodsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/payments/methods';
};

export type paymentsListPaymentMethodsResponses = {
    /**
     * Response Payments-List Payment Methods
     *
     * Successful Response
     */
    200: Array<PaymentMethodPublic>;
};

export type paymentsListPaymentMethodsResponse = paymentsListPaymentMethodsResponses[keyof paymentsListPaymentMethodsResponses];

export type paymentsCreatePaymentData = {
    body: PaymentInitiate;
    path?: never;
    query?: never;
    url: '/api/v1/payments/';
};

export type paymentsCreatePaymentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type paymentsCreatePaymentError = paymentsCreatePaymentErrors[keyof paymentsCreatePaymentErrors];

export type paymentsCreatePaymentResponses = {
    /**
     * Successful Response
     */
    200: PaymentInitiateResponse;
};

export type paymentsCreatePaymentResponse = paymentsCreatePaymentResponses[keyof paymentsCreatePaymentResponses];

export type paymentsListVehiclesWithPendingFeeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/payments/pending';
};

export type paymentsListVehiclesWithPendingFeeResponses = {
    /**
     * Response Payments-List Vehicles With Pending Fee
     *
     * Successful Response
     */
    200: Array<VehiclePublic>;
};

export type paymentsListVehiclesWithPendingFeeResponse = paymentsListVehiclesWithPendingFeeResponses[keyof paymentsListVehiclesWithPendingFeeResponses];

export type paymentsGetPaymentData = {
    body?: never;
    path: {
        /**
         * Payment Id
         */
        payment_id: string;
    };
    query?: never;
    url: '/api/v1/payments/{payment_id}';
};

export type paymentsGetPaymentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type paymentsGetPaymentError = paymentsGetPaymentErrors[keyof paymentsGetPaymentErrors];

export type paymentsGetPaymentResponses = {
    /**
     * Successful Response
     */
    200: PaymentPublic;
};

export type paymentsGetPaymentResponse = paymentsGetPaymentResponses[keyof paymentsGetPaymentResponses];

export type webhooksWompiWebhookData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/wompi';
};

export type webhooksWompiWebhookResponses = {
    /**
     * Response Webhooks-Wompi Webhook
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type webhooksWompiWebhookResponse = webhooksWompiWebhookResponses[keyof webhooksWompiWebhookResponses];

export type plansListPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/plans/';
};

export type plansListPlansResponses = {
    /**
     * Successful Response
     */
    200: PlansPublic;
};

export type plansListPlansResponse = plansListPlansResponses[keyof plansListPlansResponses];

export type plansCreatePlanData = {
    body: PlanCreate;
    path?: never;
    query?: never;
    url: '/api/v1/plans/';
};

export type plansCreatePlanErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type plansCreatePlanError = plansCreatePlanErrors[keyof plansCreatePlanErrors];

export type plansCreatePlanResponses = {
    /**
     * Successful Response
     */
    200: PlanPublic;
};

export type plansCreatePlanResponse = plansCreatePlanResponses[keyof plansCreatePlanResponses];

export type plansListAllPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/plans/all';
};

export type plansListAllPlansResponses = {
    /**
     * Successful Response
     */
    200: PlansPublic;
};

export type plansListAllPlansResponse = plansListAllPlansResponses[keyof plansListAllPlansResponses];

export type plansUpdatePlanData = {
    body: PlanUpdate;
    path: {
        /**
         * Plan Id
         */
        plan_id: string;
    };
    query?: never;
    url: '/api/v1/plans/{plan_id}';
};

export type plansUpdatePlanErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type plansUpdatePlanError = plansUpdatePlanErrors[keyof plansUpdatePlanErrors];

export type plansUpdatePlanResponses = {
    /**
     * Successful Response
     */
    200: PlanPublic;
};

export type plansUpdatePlanResponse = plansUpdatePlanResponses[keyof plansUpdatePlanResponses];

export type plansMyActiveSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/plans/subscriptions/me';
};

export type plansMyActiveSubscriptionResponses = {
    /**
     * Response Plans-My Active Subscription
     *
     * Successful Response
     */
    200: SubscriptionPublic | null;
};

export type plansMyActiveSubscriptionResponse = plansMyActiveSubscriptionResponses[keyof plansMyActiveSubscriptionResponses];

export type historyGetPaymentHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date From
         */
        date_from?: string | null;
        /**
         * Date To
         */
        date_to?: string | null;
        /**
         * Status Code
         */
        status_code?: PaymentStatusCode | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/api/v1/history/';
};

export type historyGetPaymentHistoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type historyGetPaymentHistoryError = historyGetPaymentHistoryErrors[keyof historyGetPaymentHistoryErrors];

export type historyGetPaymentHistoryResponses = {
    /**
     * Successful Response
     */
    200: PaymentsPublic;
};

export type historyGetPaymentHistoryResponse = historyGetPaymentHistoryResponses[keyof historyGetPaymentHistoryResponses];

export type historyGetParkingLogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/history/log';
};

export type historyGetParkingLogErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type historyGetParkingLogError = historyGetParkingLogErrors[keyof historyGetParkingLogErrors];

export type historyGetParkingLogResponses = {
    /**
     * Successful Response
     */
    200: ParkingLogsPublic;
};

export type historyGetParkingLogResponse = historyGetParkingLogResponses[keyof historyGetParkingLogResponses];

export type faqListFaqData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         */
        category?: string | null;
    };
    url: '/api/v1/faq/';
};

export type faqListFaqErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type faqListFaqError = faqListFaqErrors[keyof faqListFaqErrors];

export type faqListFaqResponses = {
    /**
     * Successful Response
     */
    200: FAQsPublic;
};

export type faqListFaqResponse = faqListFaqResponses[keyof faqListFaqResponses];

export type faqCreateFaqData = {
    body: FAQCreate;
    path?: never;
    query?: never;
    url: '/api/v1/faq/';
};

export type faqCreateFaqErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type faqCreateFaqError = faqCreateFaqErrors[keyof faqCreateFaqErrors];

export type faqCreateFaqResponses = {
    /**
     * Successful Response
     */
    200: FAQPublic;
};

export type faqCreateFaqResponse = faqCreateFaqResponses[keyof faqCreateFaqResponses];

export type faqDeleteFaqData = {
    body?: never;
    path: {
        /**
         * Faq Id
         */
        faq_id: string;
    };
    query?: never;
    url: '/api/v1/faq/{faq_id}';
};

export type faqDeleteFaqErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type faqDeleteFaqError = faqDeleteFaqErrors[keyof faqDeleteFaqErrors];

export type faqDeleteFaqResponses = {
    /**
     * Response Faq-Delete Faq
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type faqDeleteFaqResponse = faqDeleteFaqResponses[keyof faqDeleteFaqResponses];

export type faqUpdateFaqData = {
    body: FAQUpdate;
    path: {
        /**
         * Faq Id
         */
        faq_id: string;
    };
    query?: never;
    url: '/api/v1/faq/{faq_id}';
};

export type faqUpdateFaqErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type faqUpdateFaqError = faqUpdateFaqErrors[keyof faqUpdateFaqErrors];

export type faqUpdateFaqResponses = {
    /**
     * Successful Response
     */
    200: FAQPublic;
};

export type faqUpdateFaqResponse = faqUpdateFaqResponses[keyof faqUpdateFaqResponses];

export type supportListMyTicketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/support/';
};

export type supportListMyTicketsResponses = {
    /**
     * Successful Response
     */
    200: SupportTicketsPublic;
};

export type supportListMyTicketsResponse = supportListMyTicketsResponses[keyof supportListMyTicketsResponses];

export type supportCreateTicketData = {
    body: SupportTicketCreate;
    path?: never;
    query?: never;
    url: '/api/v1/support/';
};

export type supportCreateTicketErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type supportCreateTicketError = supportCreateTicketErrors[keyof supportCreateTicketErrors];

export type supportCreateTicketResponses = {
    /**
     * Successful Response
     */
    200: SupportTicketPublic;
};

export type supportCreateTicketResponse = supportCreateTicketResponses[keyof supportCreateTicketResponses];

export type supportUpdateTicketStatusData = {
    body: SupportTicketUpdateStatus;
    path: {
        /**
         * Ticket Id
         */
        ticket_id: string;
    };
    query?: never;
    url: '/api/v1/support/{ticket_id}/status';
};

export type supportUpdateTicketStatusErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type supportUpdateTicketStatusError = supportUpdateTicketStatusErrors[keyof supportUpdateTicketStatusErrors];

export type supportUpdateTicketStatusResponses = {
    /**
     * Successful Response
     */
    200: SupportTicketPublic;
};

export type supportUpdateTicketStatusResponse = supportUpdateTicketStatusResponses[keyof supportUpdateTicketStatusResponses];

export type pushGetPublicKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/push/public-key';
};

export type pushGetPublicKeyResponses = {
    /**
     * Response Push-Get Public Key
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type pushGetPublicKeyResponse = pushGetPublicKeyResponses[keyof pushGetPublicKeyResponses];

export type pushSubscribeData = {
    body: PushSubscriptionCreate;
    path?: never;
    query?: never;
    url: '/api/v1/push/subscribe';
};

export type pushSubscribeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type pushSubscribeError = pushSubscribeErrors[keyof pushSubscribeErrors];

export type pushSubscribeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type pushSubscribeResponse = pushSubscribeResponses[keyof pushSubscribeResponses];

export type pushUnsubscribeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Endpoint
         */
        endpoint: string;
    };
    url: '/api/v1/push/unsubscribe';
};

export type pushUnsubscribeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type pushUnsubscribeError = pushUnsubscribeErrors[keyof pushUnsubscribeErrors];

export type pushUnsubscribeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type pushUnsubscribeResponse = pushUnsubscribeResponses[keyof pushUnsubscribeResponses];

export type internalCheckExpiringPlansData = {
    body?: never;
    headers?: {
        /**
         * X-Cron-Secret
         */
        'x-cron-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/internal/check-expiring-plans';
};

export type internalCheckExpiringPlansErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type internalCheckExpiringPlansError = internalCheckExpiringPlansErrors[keyof internalCheckExpiringPlansErrors];

export type internalCheckExpiringPlansResponses = {
    /**
     * Response Internal-Check Expiring Plans
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type internalCheckExpiringPlansResponse = internalCheckExpiringPlansResponses[keyof internalCheckExpiringPlansResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
