"""auth por id de estudiante y qr, contrasena opcional

Revision ID: 0911466700b4
Revises: 5cdb9ed0daab
Create Date: 2026-09-20 16:39:07.074166

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0911466700b4'
down_revision = '5cdb9ed0daab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('qr_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_qr_token'), 'user', ['qr_token'], unique=True)
    op.create_index(op.f('ix_user_student_id'), 'user', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_student_id'), table_name='user')
    op.drop_index(op.f('ix_user_qr_token'), table_name='user')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user', 'qr_token')
    # ### end Alembic commands ###
