"""agrega student_id a user

Revision ID: 5cdb9ed0daab
Revises: 8ae6f62ae83f
Create Date: 2026-09-20 15:04:43.230528

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5cdb9ed0daab'
down_revision = '8ae6f62ae83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###
