"""respuesta admin en tickets de soporte y plan activo por defecto

Revision ID: bdb27a1f4765
Revises: e372c0075bf8
Create Date: 2026-09-20 19:16:41.909576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'bdb27a1f4765'
down_revision = 'e372c0075bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supportticket', sa.Column('admin_reply', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('supportticket', sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supportticket', 'replied_at')
    op.drop_column('supportticket', 'admin_reply')
    # ### end Alembic commands ###
