"""roles exento, plan_until, qr como jwt, push subscriptions, plan sin tipo obligatorio

Revision ID: e372c0075bf8
Revises: 0911466700b4
Create Date: 2026-09-20 17:55:48.521001

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e372c0075bf8'
down_revision = '0911466700b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pushsubscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('p256dh', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('auth', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pushsubscription_endpoint'), 'pushsubscription', ['endpoint'], unique=True)
    op.alter_column('plan', 'vehicle_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('user', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    userrole_enum = sa.Enum('ESTUDIANTE', 'EXENTO', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', userrole_enum, nullable=False, server_default='ESTUDIANTE'))
    op.add_column('user', sa.Column('plan_until', sa.Date(), nullable=True))
    op.alter_column('user', 'qr_token',
               existing_type=sa.VARCHAR(length=64),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_qr_token'), table_name='user')
    op.create_index(op.f('ix_user_qr_token'), 'user', ['qr_token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_qr_token'), table_name='user')
    op.create_index(op.f('ix_user_qr_token'), 'user', ['qr_token'], unique=True)
    op.alter_column('user', 'qr_token',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('user', 'plan_until')
    op.drop_column('user', 'role')
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.alter_column('plan', 'vehicle_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_pushsubscription_endpoint'), table_name='pushsubscription')
    op.drop_table('pushsubscription')
    # ### end Alembic commands ###
