/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutPlansRouteImport } from './routes/_layout/plans'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSupportRouteImport } from './routes/_layout/support'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlansRoute = LayoutPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSupportRoute = LayoutSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/admin': typeof LayoutAdminRoute
  '/history': typeof LayoutHistoryRoute
  '/plans': typeof LayoutPlansRoute
  '/settings': typeof LayoutSettingsRoute
  '/support': typeof LayoutSupportRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/admin': typeof LayoutAdminRoute
  '/history': typeof LayoutHistoryRoute
  '/plans': typeof LayoutPlansRoute
  '/settings': typeof LayoutSettingsRoute
  '/support': typeof LayoutSupportRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/staff': typeof StaffRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/plans': typeof LayoutPlansRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/support': typeof LayoutSupportRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/staff'
    | '/admin'
    | '/history'
    | '/plans'
    | '/settings'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/staff'
    | '/admin'
    | '/history'
    | '/plans'
    | '/settings'
    | '/support'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/staff'
    | '/_layout/admin'
    | '/_layout/history'
    | '/_layout/plans'
    | '/_layout/settings'
    | '/_layout/support'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plans': {
      id: '/_layout/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof LayoutPlansRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/support': {
      id: '/_layout/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof LayoutSupportRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutPlansRoute: typeof LayoutPlansRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSupportRoute: typeof LayoutSupportRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutPlansRoute: LayoutPlansRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSupportRoute: LayoutSupportRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
